# Generated by Django 4.2 on 2024-05-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='vehiculo_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chofer', to='registro_contabilidad.vehiculo'),
        ),
        migrations.AlterField(
            model_name='registrocontabilidad',
            name='vehiculo_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_contabilidad', to='registro_contabilidad.vehiculo'),
        ),
    ]
