# Generated by Django 5.0.6 on 2024-05-16 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej1', '0003_alter_cliente_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ej1.producto'),
        ),
    ]
